[env:pico]
platform = raspberrypi
board = pico
framework = arduino

; Serial Monitor Baudrate
monitor_speed = 115200

; Build flags
build_flags = 
    -D PICO_BUILD

; Libraries
lib_deps = 
    ; Hier Pico-spezifische Libraries eintragen
