[env:pico]
platform = raspberrypi
board = pico
framework = arduino
build_src_filter = +<*> -<toggle_gpio10_13.cpp>

[env:toggle_gpio10_13]
platform = raspberrypi
board = pico
framework = arduino
build_src_filter = -<*> +<toggle_gpio10_13.cpp>
upload_protocol = mbed
monitor_speed = 115200
build_flags =
    -D PICO_BUILD
lib_deps =
    Wire
