M48
; DRILL file KiCad 10.0.0-10.0.0~ubuntu24.04.1 date 2026-04-20T21:27:52
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-20T21:27:52+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0-10.0.0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X56.6Y-51.6
X56.6Y-123.6
X128.6Y-51.6
X128.6Y-123.6
M30
